### ISSUE TITLE
Expand documentation

### ISSUE THREAD

**Issue by Siliconrob** [Solcast/howto-pandas#1]
Add any relevant and or missing documentation

**Comment by yacheegupta** [comment]
Hi ! I am interested in adding all the relevant information regarding the project.

**Comment by Siliconrob** [comment]
Download and follow the current steps.  If there is something missing or is unclear please submit pull request with new information.

I am adding a few more details currently demonstrating [pvlib](https://github.com/pvlib/pvlib-python).

Additional resources are available here as well and I encourage you to sign up https://forums.solcast.com.au/

**Comment by Siliconrob** [comment]
Hacktoberfest only has 1 more week left, please get your contribution in before then so that it gets counted
