### ISSUE TITLE
Convert main.py code to Jupyter Notebook

### ISSUE THREAD

**Issue by Siliconrob** [Solcast/howto-pandas#2]
Create notebook from current set of code and examples

**Comment by robeartoe** [comment]
I'd love to give this a shot!

**Comment by Siliconrob** [comment]
Remember to sign up for an API key and encourage you sign up on the forums https://forums.solcast.com.au/

I need to review some things, but I anticipate the `pvlib` requirements may be tricky to get the proper ones as I had a bit of trouble getting all the correct binaries on Windows and mac OS.

Feel free to ask for help

**Comment by robeartoe** [comment]
Okay I got a notebook going. #3 

Interestingly enough, I couldn't get the install for netCDF4 to work on mac. I had to brew install HDCF5, tried to, but I didn't have enough time to install. 

But I got it to work on my linux comptuer at home though.

**Comment by Siliconrob** [comment]
This is great.  If there are any other issues you remember  with mac OS because other people will probably encounter these feel free to add them to the README
